[workspace]
resolver = "3"
exclude = ["zama"]
members = [
    "programs/*"
]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
anchor-lang = "1.2.0"
bytemuck = "1.25.2"
zama-fhe = { path = "zama/solana/crates/zama-fhe", version = "0.1.0" }
zama-host = { path = "zama/solana/programs/zama-host", version = "0.1.0" }
